apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: knative-app
  namespace: openshift-gitops
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: knative
    repoURL: https://github.com/lordofthejars/cloud-citizen.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: false